### ISSUE TITLE
Serial connection

### ISSUE THREAD

**Issue by flazzarini** [bimbar/pykwb#2]
Hi there. Do you have any schematics/plans or tutorials on how to access the serial port of a KWB Easyfire? Thanks for any help.

**Comment by canatella** [comment]
Be sure to cut the power to the boiler. 
Remove the front panel by lifting it up. 
Unscrew the two bolts at the bottom, remove that second panel. 
One of those green plugs is the RS485, it's named "BUS/24V" I think, or something like that, there are a "A" and "B" labelled port there that are the two RS485 channel that you need to connect.

**Comment by bimbar** [comment]
Sorry, I don't seem to have noticed this one. Thanks for answering.
